### ISSUE TITLE
State "type" is called twice

### ISSUE THREAD

**Issue by SpyTec** [SpyTec/EDAssets#1]
Currently, `type` in app.js calls the function AssetType twice, from what I understand this has been a bug which is resolved in the latest non-stable builds where if you have parameters in together with `$stateProvider`, such as `{this}` or `:this`. Removing such parameters removes the double-call.

If anyone has a work-around that would be great (or if I've just messed up something)

**Comment by cmmcleod** [comment]
Is there any reason it needs to be wrapped in `{ }`?

`url: '/type?file',`

Should work

**Comment by SpyTec** [comment]
Well, the stateProviders contain url, templateUrl and controller, which is why that wouldn't work? Here's one of them in the code (oh and sorry for late answer)

    $stateProvider.state('type', {
        url: '/type?{file}',
        templateUrl: 'js/directives/displayType.html',
        controller: 'AssetType'
    });

**Comment by SpyTec** [comment]
Closed due to migration to VueJS
