### ISSUE TITLE
Vectorize codex organic structures icon

### ISSUE THREAD

**Issue by Venefilyn** [SpyTec/EDAssets#100]
![i_view32_2019-01-02_22-22-23](https://user-images.githubusercontent.com/6598829/50613161-f7882700-0edc-11e9-9f54-1fbffe1cf85a.png)

**Comment by Maximilian1271** [comment]
Hope this helps
svg can be found here: https://drive.google.com/open?id=15iXZw9Cl0hfMqWviYdBZsxk-gg0DQ-Zp

![organiccodex](https://user-images.githubusercontent.com/1573345/50716405-c1d07300-1081-11e9-9b88-21833726f4c9.png)

**Comment by Maximilian1271** [comment]
Sorry but i encountered a critical error in this svg and had to update it.. I would advise you to update this as soon as possible! GDrive link stays the same!

orginal svg had messy contours, as can be seen here 
![image](https://user-images.githubusercontent.com/1573345/50734666-a27d3700-11a2-11e9-96aa-f545fa2cba71.png)

**Comment by SpyTec** [comment]
It's been fixed
