### ISSUE TITLE
Vectorize codex thargoid and guardian location icon

### ISSUE THREAD

**Issue by Venefilyn** [SpyTec/EDAssets#101]
![i_view32_2019-01-02_22-23-25](https://user-images.githubusercontent.com/6598829/50613197-12f33200-0edd-11e9-89d7-123b9dea5bdd.png)

**Comment by Maximilian1271** [comment]
Hope this can be of use ^^
svg can be found here: https://drive.google.com/open?id=1QmjciuNzqi9UP8-ao-pKz9tXcApYCpvO

![thargoidcodex](https://user-images.githubusercontent.com/1573345/50715608-5f29a800-107e-11e9-94ad-f6b4d809bf62.png)
