### ISSUE TITLE
Vectorize mini-federation icon

### ISSUE THREAD

**Issue by SpyTec** [SpyTec/EDAssets#115]
Taken from browse squadrons page
![i_view32_2019-01-02_22-42-50](https://user-images.githubusercontent.com/6598829/50614038-d70d9c00-0edf-11e9-85ed-efb0fe4ff0bf.png)

**Comment by Zhincore** [comment]
https://zhincore.eu/storage/mini-federation_icon.png
https://zhincore.eu/storage/mini-federation_icon.svg

![mini-federation icon](https://zhincore.eu/storage/mini-federation_icon.png)
