### ISSUE TITLE
Elite Rank badges

### ISSUE THREAD

**Issue by Tilleen** [SpyTec/EDAssets#122]
Is there any problem with me create 3d models of your rank badges. These are aimed at being able to be 3d printed? I will probably upload them to thingiverse when finished.

**Comment by SpyTec** [comment]
It's probably not a problem, as long as it's not commercialized I don't think you would break Frontier's community license. 

From my side you're allowed to take the assets and make 3D models, but keep in mind you have to follow Frontier's community license as well
