### ISSUE TITLE
Delacy Icon

### ISSUE THREAD

**Issue by DRA6N** [SpyTec/EDAssets#152]
**Is this a finished asset?**
- [X] Finished asset
- [ ] Asset request

**What type of asset is this?**
- [X] Icon
- [ ] Concept art

**Delacy Icon
![Delacy](https://user-images.githubusercontent.com/9896716/124345159-1211e880-db8c-11eb-870d-12b8f6b9a94c.png)
**

**Does the following exist?**
- [ ] SVG file
- [X] PNG file
- [ ] JPG file

**Comment by Venefilyn** [comment]
Thanks! But it's already present on [manufacturers page](https://edassets.org/#/manufacturers) 

![Faulcon Delacy](https://edassets.org/static/img/manufacturers/FaulconDelacy.png)
