### ISSUE TITLE
All Character Portraits

### ISSUE THREAD

**Issue by DJScias** [SpyTec/EDAssets#2]
Hello there,

Thought I'd donate the remaining character portraits that I extracted from the game and put up on the ED Wiki considering I noticed they weren't on the site yet.

Link to the winrar file: https://mega.co.nz/#!F1120AqB!8Q1scyxzRMuTdOHzCsjwtkv29pOctE6SFJUiNcvzlVs
(Edit: Changed the link to include the proper Zachery Hudson file.)

Hope it helps you out.

Kind regards,
DJScias

**Comment by SpyTec** [comment]
Cheers, I added it in d55a45bae266bf94fb7ce16060f50847550b0be2.

I just wish we had the high-quality version Frontier is keeping for themselves atm
