### ISSUE TITLE
Vectorize more decals

### ISSUE THREAD

**Issue by freiheit** [SpyTec/EDAssets#25]
Attached..

![decals-overview](https://cloud.githubusercontent.com/assets/19813/20026462/1dc5b420-a2b8-11e6-8f48-1e0d79e26a14.png)
![decal-aedc](https://cloud.githubusercontent.com/assets/19813/20026465/227389d4-a2b8-11e6-9826-d7d9ca59f75c.png)
![decal-black-birds-squadron](https://cloud.githubusercontent.com/assets/19813/20026467/24475b5a-a2b8-11e6-97a3-56bc7eb686f1.png)
![decal-eg](https://cloud.githubusercontent.com/assets/19813/20026470/263668fc-a2b8-11e6-9d2f-410eb7731675.png)
![decal-galcop](https://cloud.githubusercontent.com/assets/19813/20026473/2d0776e4-a2b8-11e6-8c25-8a2319e1baa9.png)
![decal-interstellar-communists](https://cloud.githubusercontent.com/assets/19813/20026474/2f424600-a2b8-11e6-964f-bdd164f6345c.png)
![decal-pax](https://cloud.githubusercontent.com/assets/19813/20026476/32935c72-a2b8-11e6-9bcf-a63eea8d64a0.png)
![decal-skull](https://cloud.githubusercontent.com/assets/19813/20026477/353b07d6-a2b8-11e6-8d0d-eb8b590b3ef2.png)
![decal-wolves](https://cloud.githubusercontent.com/assets/19813/20026480/3af467f8-a2b8-11e6-8ba1-b46b7f6f7404.png)

**Comment by SpyTec** [comment]
PAX icon already exists in their official logo. We already have the planet vectorized already and we're not going to cover player group icons as the groups themselves have the vector already

Only one of interest is the Pirate one but that is already mentioned in #16 so I'm closing this one :P
