### ISSUE TITLE
Icon for Engineer

### ISSUE THREAD

**Issue by freiheit** [SpyTec/EDAssets#26]
Hexagon with a circle inside it. Appears "engineers" and on galaxy map. Sometimes looks almost like there's an attempt at a subtle 3d effect, to make it look like a nut.

![engineer-1](https://cloud.githubusercontent.com/assets/19813/20248285/7af57278-a995-11e6-9a4c-2490f20268b3.png)
![engineer-2](https://cloud.githubusercontent.com/assets/19813/20248289/7af5b2ce-a995-11e6-9986-72373004018a.png)
![engineer-3](https://cloud.githubusercontent.com/assets/19813/20248287/7af58df8-a995-11e6-95bd-515be553baff.png)
![engineer-4](https://cloud.githubusercontent.com/assets/19813/20248290/7af57e9e-a995-11e6-9f62-000dc2a4ff6c.png)
![engineer-5](https://cloud.githubusercontent.com/assets/19813/20248286/7af57430-a995-11e6-9936-249d65a75b18.png)
![engineer-6](https://cloud.githubusercontent.com/assets/19813/20248288/7af5c75a-a995-11e6-979a-8c1998cdd9df.png)

**Comment by SpyTec** [comment]
Sure, I'll get on it soon™

**Comment by SpyTec** [comment]
I got it vectorized from someone on email. Will bring it up on website around mid-August

**Comment by SpyTec** [comment]
Now added in 98e6e0b5d27f7dd5dcbf73f94d3ee4e454b6927c
