### ISSUE TITLE
Buttonized Elite Rank SVGs

### ISSUE THREAD

**Issue by ToBeFree** [SpyTec/EDAssets#31]
Using the Inkscape "buttonize" filter, I created these four SVGs for a video. I was inspired by the icons INARA uses to display ranks, but these have been too small for me, so I tried to create a similar effect in SVG. For the trading rank, I had to resize the decoration a bit; it would else have overlapped the Elite icon.

Maybe you'd like to add these to the page. :)

[elite-rank-buttons.zip](https://github.com/SpyTec/EDAssets/files/1058009/elite-rank-buttons.zip)
![explorationelite-button](https://user-images.githubusercontent.com/1029811/26879288-d94849b6-4b90-11e7-8c9c-f6dc614596e1.png)
![tradingelite-button](https://user-images.githubusercontent.com/1029811/26879289-d9763bdc-4b90-11e7-84dc-cb88165aa4e0.png)
![combatelite-button](https://user-images.githubusercontent.com/1029811/26879290-d979a588-4b90-11e7-8f14-70833489f6d1.png)
![cqcelite-button](https://user-images.githubusercontent.com/1029811/26879291-d97c29de-4b90-11e7-8ba5-1be0ce1ed134.png)

Inkscape and "normal" SVGs included.

**Comment by SpyTec** [comment]
As this is more of a stylized vector of the already existing vectors it's not really for EDAssets, especially so when they don't look like that anywhere in the game

Thanks anyway!

**Comment by SpyTec** [comment]
Probably better to post it by itself on Reddit or the forums

**Comment by ToBeFree** [comment]
Oh, ok. I'll do that then, thanks. :)

I've uploaded them here for now: https://github.com/ToBeFree/EDAdditionalAssets
