### ISSUE TITLE
ED Loader

### ISSUE THREAD

**Issue by cmmcleod** [SpyTec/EDAssets#4]
I've created a loader which is similar to the in game loader:

https://gist.github.com/cmmcleod/e77e79131a8254c14cf8

The SVG can always be embedded as pure HTML and the CSS/LESS can be tuned:

http://codepen.io/cmmcleod/pen/meQqRK

Could be a potential addition to Animated Logos or Misc. Icons?

Love your site btw, I only just discovered it, some I'm going to be using it a lot for Coriolis.io.

**Comment by SpyTec** [comment]
Hey!

Thanks for the animation, just remembered that [EDCodex](http://edcodex.info/) guys made a similar one here
http://codepen.io/anon/pen/VvmeQE?editors=110 

Oh and there was also someone who added a HTML/CSS-only one
http://codepen.io/essidus/pen/VvmLjo?editors=110

I will see if I can possibly add all three.

**Comment by cmmcleod** [comment]
I actually made

http://codepen.io/anon/pen/VvmeQE?editors=110

and give it to @gbiobob and @wolverine2710 :)

**Comment by SpyTec** [comment]
Added it in 3a06536b3a0e33a48cbe2899ac2eaba68f1f2ec8 :)
