### ISSUE TITLE
Navigation drawer needs two clicks to open

### ISSUE THREAD

**Issue by SpyTec** [SpyTec/EDAssets#46]
If navigation drawer/left sidebar is closed it needs two clicks to be able to open. Not tested other browsers or devices yet

Firefox 63.0 (64-bit)

**Comment by SpyTec** [comment]
Confirmed on Twitter on mobile devices

**Comment by SayakMukhopadhyay** [comment]
This bug was seen in older Vuetify versions and is probably a vuetify issue. Updating the dependencies should fix this.

**Comment by SpyTec** [comment]
Seems to be fixed, thanks @SayakMukhopadhyay

**Comment by SpyTec** [comment]
The issue is back again on website

**Comment by SpyTec** [comment]
Should be fixed in acd0fb22491b804c5be52a4f888abb14e1bf1b4a
