### ISSUE TITLE
Fix GalNet logo to be 7 arms, not 8

### ISSUE THREAD

**Issue by Venefilyn** [SpyTec/EDAssets#47]
Although current GalNet vector was traced from an in-game 8-arm GalNet image, it is outdated as current in-game logo has changed to 7 arms instead.

**Comment by TalShaf** [comment]
I gave it a shot. Let me know if there are any issues. 

https://www.dropbox.com/sh/yqprazikqtaydhx/AAAMxW9dpxH5Jze4Q6ICdHHga?dl=0

**Comment by SpyTec** [comment]
Overall pretty good, I highlighted some areas. I feel like the GalNet logo itself is pointy, but not seen high-res pictures of the 7-arm one to know

With roundness it all keeps turning left, never going right, which I highlighted in middle. Som arms have flat top whilst others are rounded

![](https://i.imgur.com/5uHvnVo.png)

**Comment by TalShaf** [comment]
What do you mean by 'with roundness it all keeps turning left'?

**Comment by SpyTec** [comment]
All the outside lines never turn right, they keep turning left. If image below makes sense, the lines show direction of the arms. Circled area in middle shows it starting from middle in the wrong direction

![](https://i.imgur.com/RyyrIRZ.png)

**Comment by TalShaf** [comment]
Sorry, not sure what you mean. I'll try again with higher resolution image.

**Comment by TalShaf** [comment]
![galnet wip](https://user-images.githubusercontent.com/30076917/47953058-37cc3700-df78-11e8-8647-e49d30647a99.png)

Is this better?

**Comment by TalShaf** [comment]
Original link updated with new versions.

**Comment by SpyTec** [comment]
Want the link to be to GitHub profile?

**Comment by TalShaf** [comment]
https://twitter.com/CMDR_Deonon
