### ISSUE TITLE
Galaxy Map Assets

### ISSUE THREAD

**Issue by WaldemarLehner** [SpyTec/EDAssets#63]
[export.zip](https://github.com/SpyTec/EDAssets/files/2565662/export.zip)
Please add these icons under the Galaxy Tab, perfabs under a subgrouping like "Galaxy Map Markers" or similar.

**Comment by SpyTec** [comment]
Hey, that's great. I'll add it when I'm home.

One question though, the community goal isn't aligned correctly, if we draw a horizontal line on on the top of the yellow marker we will see there's a height difference between the two top ones. Can this be fixed?

**Comment by WaldemarLehner** [comment]
![image](https://user-images.githubusercontent.com/27686785/48272016-f1764c80-e43d-11e8-946f-dcff853f6682.png)
is this better?

**Comment by SpyTec** [comment]
Looks better :+1:

**Comment by WaldemarLehner** [comment]
Aight. sweet. Repacking the zip :)

**Comment by WaldemarLehner** [comment]
[export.zip](https://github.com/SpyTec/EDAssets/files/2566455/export.zip)

**Comment by SpyTec** [comment]
@WaldemarLehner With the friends marker, do you have a reference image for the people icons themselves? As the one I have made on EDAssets looks like this

![](https://edassets.org/static/img/galaxy-map/Friends-galaxy-map.png)

**Comment by SpyTec** [comment]
Yes I used the same one, this is the reference image I used, which to me looks more like the one I posted. Though my one is 3 years old or so

![screenshot_0382_friends](https://user-images.githubusercontent.com/6598829/48678884-c69c9e80-eb89-11e8-9bf2-a781fc6f664e.png)

**Comment by WaldemarLehner** [comment]
yeah. should be the same ref pic

**Comment by WaldemarLehner** [comment]
The "person" in the background looks like it has a darker green on the reference though.

**Comment by SpyTec** [comment]
That is true. Unless you have any objections I will replace the people in your marker icon to the one currently on EDAssets, and change the colour of the second person accordingly
