### ISSUE TITLE
Triple Elite Decal

### ISSUE THREAD

**Issue by RedTwoEcho** [SpyTec/EDAssets#64]
https://imgur.com/7xTCQA7

There's a cool new triple elite decal on the beta currently, just wondering if you could turn it into a png or svg for us to all use. Cheers!

**Comment by SpyTec** [comment]
Hey. Yes it’s on my todo list. I can’t give an estimate though

**Comment by RedTwoEcho** [comment]
Thanks dude and take your time

**Comment by WaldemarLehner** [comment]
![trippleelite 10x](https://user-images.githubusercontent.com/27686785/48483775-a761e200-e814-11e8-85cf-ce618bf9953b.png)

Did this quickly using https://edassets.org/static/img/ed-logos/elite-dangerous-clean.svg. Might be a bit off though

**Comment by WaldemarLehner** [comment]
[trippleelite.zip](https://github.com/SpyTec/EDAssets/files/2580791/trippleelite.zip)

**Comment by SpyTec** [comment]
@WaldemarLehner Looks good! Two things I see right off the bat though, the planet lines (circle starting from top) should end in the second valley of the bottom circle thing.. (whatever it's called). So it just ends prematurely

Then there's also a size difference in the stars by looking at the decals list on the left

**Comment by SpyTec** [comment]
@WaldemarLehner Any updates on this?

**Comment by WaldemarLehner** [comment]
Whoops. forgot about it. Can do it tomorrow.

**Comment by SpyTec** [comment]
This part 

![firefox_2018-11-25_22-40-55](https://user-images.githubusercontent.com/6598829/48984984-34554700-f103-11e8-9320-43c52d3512c6.png)

**Comment by WaldemarLehner** [comment]
![image](https://user-images.githubusercontent.com/27686785/48999838-17972e80-f158-11e8-8ca3-828931de60ae.png)

**Comment by WaldemarLehner** [comment]
[edassets.zip](https://github.com/SpyTec/EDAssets/files/2621929/edassets.zip)

**Comment by SpyTec** [comment]
Yes sorry, that looks great. Still a very tiny difference with the stars. But I'll fix that now and add it with credits going to you

**Comment by SpyTec** [comment]
Added in 2c9fabeceac18e6096c6ce282b1c723db3358093 and it is live on [Decals category](https://edassets.org/#/decals)
