### ISSUE TITLE
Vectorize "Join a Squadron" icon

### ISSUE THREAD

**Issue by SpyTec** [SpyTec/EDAssets#74]
Vectorize and add to Squadrons category. If possible grab a higher res before trying to vectorize

![screenshot_20181211_164809](https://user-images.githubusercontent.com/6598829/49811956-9ef1be00-fd64-11e8-96a4-9383abced564.png)

**Comment by SpyTec** [comment]
@Zhincore Do you have a place you want linked for the credit? I've prepared the following, looks good?

```json
"designer_info": [
  {
    "name":"CMDR Zhincore",
    "url":"https://github.com/Zhincore"
  }
],
```

**Comment by Zhincore** [comment]
Yes. Anything is okay

**Comment by SpyTec** [comment]
Now live in [squadrons category](https://edassets.org/#/squadrons)
