### ISSUE TITLE
Made a planet icon

### ISSUE THREAD

**Issue by Zhincore** [SpyTec/EDAssets#82]
Couldn't really find it anywhere, so i edited the "Courier to planet" icon.
https://zhincore.eu/storage/planet.png
https://zhincore.eu/storage/planet.svg

**Comment by SpyTec** [comment]
Not sure where to place this one. I was thinking of putting it under a subcategory in Galaxy Map category. Thoughts?

**Comment by Zhincore** [comment]
I'm unsure too. I think your idea might work

**Comment by SpyTec** [comment]
It's been added. Put it in the main galaxy map category
