### ISSUE TITLE
Remade Surface Port Planetary Map icon to match in-game icon better

### ISSUE THREAD

**Issue by Zhincore** [SpyTec/EDAssets#83]
https://zhincore.eu/storage/surface_port_pm.svg
https://zhincore.eu/storage/surface_port_pm.png

**Comment by SpyTec** [comment]
I can't remember where this is from. On the planetary view, this is how it looks like 

![](https://i.imgur.com/g2wjV44.png)

**Comment by Zhincore** [comment]
Ah yes, it actually is. Didn't noticed it looks different on map

**Comment by SpyTec** [comment]
Added in db8d92284dcafe5b1b4262b87d2d9e79e18a620f
