### ISSUE TITLE
Vectorize system map icons

### ISSUE THREAD

**Issue by SpyTec** [SpyTec/EDAssets#84]
There are two icons missing from EDAssets from system map view. Only the dark should be vectorized and not the box itself.

- [ ] Add Orrery map icon
- [ ] Add normal map icon

Orrery icon:

![i_view32_2019-01-02_20-26-10](https://user-images.githubusercontent.com/6598829/50608810-04514e80-0ece-11e9-82aa-41b829d54f25.png)

Normal icon:

![i_view32_2019-01-02_20-27-42](https://user-images.githubusercontent.com/6598829/50608818-09ae9900-0ece-11e9-837d-71d023e96ebd.png)

**Comment by Zhincore** [comment]
Like this?
https://zhincore.eu/storage/orrery_map.png
https://zhincore.eu/storage/orrery_map.svg

https://zhincore.eu/storage/normal_map.png
https://zhincore.eu/storage/normal_map.svg

![Orrery map](https://zhincore.eu/storage/orrery_map.png)
![Normal map](https://zhincore.eu/storage/normal_map.png)

**Comment by SpyTec** [comment]
Yes, like that. Looks good!

I'll add it soon. Unsure about the gap between the planets and the orbital rings, but can't really do much without a better picture

**Comment by SpyTec** [comment]
It's now live
